### ISSUE TITLE
Will continue developtmet?

### ISSUE THREAD

**Issue by salvadorc17** [EmileSonneveld/Contra_remake#1]
You have new plans for this game remake, seems promising and with some extra features like networking will be really cool

**Comment by EmileSonneveld** [comment]
It is a remake of an existing game. It would defeat the purpose to add extra features ;)
The original game allows a second offline player. That would be very cool indeed

**Comment by salvadorc17** [comment]
Yes it does, but do you will not continue developtment?, addig other features is not bad idea.

**Comment by EmileSonneveld** [comment]
I'll probably not continue on further developing no. I mostly made it to learn c++, If you wan't to play a more complete version, there is a java clone somewhere on the web.

Someone implemented an AI with this code as base. I'll poll how that went :)

**Comment by salvadorc17** [comment]
Can you give me some links, thanks.
